### ISSUE TITLE
The Temp Monitor CPU module is not working properly.

### ISSUE THREAD

**Issue by Rak1ta** [raspberrypi-ui/lxplug-cputemp#4]
In the process of switching to Bullseye, I installed applications and noticed a bug. With nixnote2 installed, no panels are displayed on the desktop when the temperature display module is installed.

How this can be revealed:
1. Installed a clean Bullseye x64;
2. Installed the lxplug-cputemp module on the application panel;
3. Rebooted, or _**lxpanelctl restart**_
4. Everything works;
5. _**sudo apt install nixnote2**_
6. Rebooted, or _**lxpanelctl restart**_
7. The bug appears, the panel cannot be displayed

And it only works with the nixnote2 package itself
On my Buster armhf everything works fine, the bug manifested itself on Bullseye aarch64.

**Comment by Rak1ta** [comment]
@spl237 I would be happy to provide more information, but I don't know how to track the error.

**Comment by Botspot** [comment]
Can reproduce. Lxpanel worked before installing nixnote2, and it did not work afterwards. Restarting lxpanel with Chromium maximized merely caused my Chromium window to repeatedly resize to cover all the screen, then it resized to accommodate a panel-sized area on the screen, then back to fullscreen again. This repeated about once a second with high CPU usage, so I hypothesize that lxpanel was continuously trying to restart.

To view errors, I killed lxpanel with `killall lxpanel` and then ran it in a terminal with `lxpanel --profile LXDE-pi`.
Here was the output:
```
$ lxpanel --profile LXDE-pi
** Message: 12:26:31.333: x-terminal-emulator has very limited support, consider choosing another terminal
** Message: 12:26:31.906: netman: network manager service not running; plugin hidden
** Message: 12:26:31.954: Connecting ...
** Message: 12:26:31.954: Status changed to down
** Message: 12:26:31.955: Status changed to opened
** Message: 12:26:31.955: Connected to dhcpcd-8.1.2
** Message: 12:26:31.956: Status changed to connected
** Message: 12:26:31.956: eth0: CARRIER
** Message: 12:26:31.956: eth0: Configured 10.31.157.71/24
** Message: 12:26:31.956: wlan0: Not associated
** Message: 12:26:31.958: wlan0: WPA status connected
** Message: 12:26:32.329: cputemp: Added sensor /sys/class/thermal/thermal_zone0/
** Message: 12:26:32.329: cputemp: Found 1 sensors
** Message: 12:26:32.451: ptbatt: battery 0 not found
grep: write error: Broken pipe

(lxpanel:9657): Gtk-WARNING **: 12:26:34.742: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
Segmentation fault
```
Purging nixnote2 prevented the segmentation fault and allowed lxpanel to launch normally.
This is the output from that successful test:
```
** Message: 12:30:10.575: x-terminal-emulator has very limited support, consider choosing another terminal
** Message: 12:30:11.115: netman: network manager service not running; plugin hidden
** Message: 12:30:11.162: Connecting ...
** Message: 12:30:11.162: Status changed to down
** Message: 12:30:11.163: Status changed to opened
** Message: 12:30:11.163: Connected to dhcpcd-8.1.2
** Message: 12:30:11.163: Status changed to connected
** Message: 12:30:11.163: eth0: CARRIER
** Message: 12:30:11.163: eth0: Configured 10.31.157.71/24
** Message: 12:30:11.163: wlan0: Not associated
** Message: 12:30:11.165: wlan0: WPA status connected
** Message: 12:30:11.556: cputemp: Added sensor /sys/class/thermal/thermal_zone0/
** Message: 12:30:11.556: cputemp: Found 1 sensors
** Message: 12:30:11.685: ptbatt: battery 0 not found
grep: write error: Broken pipe

(lxpanel:10055): Gtk-WARNING **: 12:30:12.205: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
```
Since the pixbuf error is still there, this means it is not the cause of the issue.

Please note that this segfault seems to be solely caused by the nixnote2 package, as I left its dependencies in-place for a successful lxpanel test.

**Comment by Botspot** [comment]
I installed nixnote2 again to test running lxpanel with `strace`.
These are the final few lines that I feel are useful:
```
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
ppoll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=17, events=POLLIN}, {fd=19, events=POLLIN}], 4, {tv_sec=0, tv_nsec=0}, NULL, 0) = 0 (Timeout)
openat(AT_FDCWD, "/sys/class/thermal/thermal_zone0/temp", O_RDONLY) = 14
fstat(14, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0
read(14, "56965\n", 4096)               = 6
close(14)                               = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV +++
Segmentation fault
```
To reproduce this, just run `strace lxpanel --profile LXDE-pi`. You may need to install the `strace` package first.

**Comment by spl237** [comment]
OK, thanks for the detailed report - I am not sure why a note package would be interfering with the CPU monitor, but it looks as if it is! 

I'm not sure when I will have time to look at this - things are very busy at the moment - but will do so as soon as possible. For now, just not using the CPU temperature plugin is probably the best thing to do.

**Comment by Rak1ta** [comment]
Similar to `libreoffice`. The bug may not work, but the next time you restart, `lxpanelctl` no longer starts. I hope it helps. In addition to turning on the SSH/VNC/I2C, changing the panel settings, the OS update did nothing. I never figured out how to 100% cause this bug.

[trace_output.txt](https://github.com/raspberrypi-ui/lxplug-cputemp/files/11190782/trace_output.txt)
[trace_output_error.txt](https://github.com/raspberrypi-ui/lxplug-cputemp/files/11190783/trace_output_error.txt)

`sudo apt upgrade`
`sudo reboot`
`killall lxpanel`
`strace lxpanel --profile LXDE-pi`
`sudo apt install libreoffice`
`killall lxpanel`
`strace lxpanel --profile LXDE-pi`

**Comment by Rak1ta** [comment]
This error is also obtained with `libreoffice`. The bug may not work, but the next time you restart, `lxpanelctl` no longer starts. I hope it helps. In addition to turning on the SSH/VNC/I2C, changing the panel settings, the OS update did nothing. I never figured out how to 100% cause this bug.

[trace_output.txt](https://github.com/raspberrypi-ui/lxplug-cputemp/files/11190782/trace_output.txt)
[trace_output_error.txt](https://github.com/raspberrypi-ui/lxplug-cputemp/files/11190783/trace_output_error.txt)

`sudo apt upgrade`
`sudo reboot`
`killall lxpanel`
`strace lxpanel --profile LXDE-pi`
`sudo apt install libreoffice`
`killall lxpanel`
`strace lxpanel --profile LXDE-pi`

At the same time (after the teams above), `strace lxpanel --profile LXDE-pi`/`lxpanelctl restart`, the error remains.
With this command, the desktop starts, or `sudo reboot` (to the first `killall`):
```
pi@raspberrypi:~ $ strace -o trace_output.txt lxpanel --profile LXDE-pi
** Message: 16:47:03.004: x-terminal-emulator has very limited support, consider choosing another terminal

** (lxpanel:2556): WARNING **: 16:47:03.010: The directory '/home/pi/Templates' doesn't exist, ignoring it
** Message: 16:47:04.074: cputemp: Added sensor /sys/class/thermal/thermal_zone0/
** Message: 16:47:04.074: cputemp: Found 1 sensors
** Message: 16:47:04.582: netman: network manager service not running; plugin hidden
** Message: 16:47:04.624: Connecting ...
** Message: 16:47:04.625: Status changed to down
** Message: 16:47:04.627: Status changed to opened
** Message: 16:47:04.628: Connected to dhcpcd-8.1.2
** Message: 16:47:04.631: Status changed to connected
** Message: 16:47:04.631: eth0: CARRIER
** Message: 16:47:04.632: eth0: Configured XXX.XXX.X.XXX/XX
** Message: 16:47:04.632: wlan0: Not associated
** Message: 16:47:04.650: wlan0: WPA status connected
** Message: 16:47:05.121: ptbatt: battery 0 not found

** (lxpanel:2556): WARNING **: 16:47:05.533: launchbar: desktop entry does not exist
```

**Comment by Botspot** [comment]
Same here. Lxpanel crashes with a segfault when the cpu temperature module is enabled and when Libreoffice is installed.

**Comment by Rak1ta** [comment]
The bug has been fixed,  everything works.
