### ISSUE TITLE
Why are you deleting github issues?

### ISSUE THREAD

**Issue by Botspot** [raspberrypi-ui/lxplug-cputemp#6]
I recall an issue being opened on this repo a few weeks ago. It primarily reported segmentation faults caused when nixnote2 was installed and the CPU Temperature plugin was enabled on lxpanel. Furthermore, I discovered the same segfault when libreoffice was installed. At the time, the recommended course of action was to disable the CPU temperature plugin for the time being.

Well, I left this tab open in my browser and upon looking through the rest of my tabs today I noticed that the bug report no longer exists! I went through my Chrome history to find the original title of the issue. "The Temp Monitor CPU module is not working properly. "
Here is a screenshot.
![Screenshot from 2023-04-21 10-14-19](https://user-images.githubusercontent.com/54716352/233673018-ebccf08b-2d1f-4e81-aceb-cb2f74ff344a.png)
And here is now broken link to that issue: https://github.com/raspberrypi-ui/lxplug-cputemp/issues/4

This worries me, as I cannot think of any legitimate reason to delete an issue that highlights a problem with your software. If the problem was resolved with a bugfix, the issue should be closed and the people reporting the issue should be informed about the findings. That is our course of action over at [Pi-Apps](https://github.com/Botspot/pi-apps).
I have experienced issue-deletion before, but it was on closed-source corporate bugtracker websites which took pride in the small number of bug reports they had. They repeatedly ignored my reports of crashes and glitches, choosing instead to delete my bug reports out of existence.

However, due to the positive interactions I have had with the Raspberry Pi Foundation in the past, and since this organization holds a very high standing in the community, I choose not to make assumptions about this situation. Maybe it was a legitimate mistake. Perhaps instead, there was a valid reason to delete the issue that I am not aware of. This is your opportunity to explain what happened and why.

**Comment by spl237** [comment]
Since raising the issue, the user who did so has deleted their account - or had it deleted by GitHub; I don't know which. 

As a result of this, any issues raised by that user, including this one, were automatically deleted by GitHub - nothing to do with us; to my knowledge we have never deleted any issues raised in this repo.

The issue in question has been fixed, as you will see if you do a sudo apt update.

**Comment by Botspot** [comment]
Thank you, Simon.

**Comment by Botspot** [comment]
@spl237, I checked back to some issues that have been opened on our repos by users that later closed their accounts.

- https://github.com/Botspot/pi-apps/issues/613
- https://github.com/Botspot/pi-apps/issues/505

Those issues are still there - not deleted when the user deleted their account. Also, ChatGPT agreed that issues should stay intact after the author's account deletion.
![Screenshot from 2023-04-21 12-49-16](https://user-images.githubusercontent.com/54716352/233702105-2a8f59db-203f-475f-9f9f-876357dfb884.png)
Any further ideas?

**Comment by ghollingworth** [comment]
GitHub said "hidden due to the status of the account of the user who opened the issue"

(The person was Russian, I'm not sure if that's relevant or not...)

**Comment by Botspot** [comment]
Well I learned something today. Thanks to both of you for quick replies and I wish you a wonderful day.
